### ISSUE TITLE
Use momentjs to remove snowflakes for spring

### ISSUE THREAD

**Issue by seafoam6** [DetroitJS/detroitjs-com#29]
Branching off of Mike's PR, auto-remove snowflakes in Feb-Nov based on current month.

**Comment by seanohue** [comment]
Since we live in Michigan, I suggest keeping the snowflakes around until at least April. For realism.

**Comment by seafoam6** [comment]
Maybe this should ping a weather API. We might need a Rain component.

**Comment by seafoam6** [comment]
Ooops. already does this.
