### ISSUE TITLE
Images uploaded to Meetup break

### ISSUE THREAD

**Issue by seafoam6** [DetroitJS/detroitjs-com#34]
![screen shot 2018-01-09 at 4 22 34 pm](https://user-images.githubusercontent.com/1787498/34743907-6ad88b9e-f559-11e7-96f2-5ec4ecd2d0b3.png)

**Comment by mgmatola** [comment]
Don't know if this is the problem, but httpss looks like it has too many s's.

**Comment by seafoam6** [comment]
see https://github.com/DetroitJS/detroitjs-com/pull/35

**Comment by seafoam6** [comment]
There's a snake horror movie called "sssssssss".

**Comment by seafoam6** [comment]
FIXED
