### ISSUE TITLE
Move meetup API fetching to internal next server

### ISSUE THREAD

**Issue by sixlive** [DetroitJS/detroitjs-com#39]
This will allow me to remove the need for the server and then we can move and host on netlify.

**Comment by imcodingideas** [comment]
I can do this! However; I could move this to NetlifyCMS

**Comment by imcodingideas** [comment]
I'll do this over the weekend. I will also upgrade gatsby to v2. Sorry, it's taken this long.

**Comment by sixlive** [comment]
No worries dude! Excited to see how you work with netlify CMS
