### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by sixlive** [DetroitJS/detroitjs-com#4]
Need to implement some linting as part of the build process. Looking at ESLint and the [Airbnb presets](https://github.com/airbnb/javascript).

**Comment by glidej** [comment]
Do you want the errors that linting finds as a separate PR?

**Comment by sixlive** [comment]
Yes please. I also am torn between standard JS and airbnb standards. Any preference and why?

I've always personally leaned towards standard JS. Not sure why I specified airbnb in the issue.

**Comment by glidej** [comment]
I've never used either; we've inherited a config or rolled our own in the past. It looks like Next themselves use Standard, but Airbnb seems to be vastly more popular. I submitted a PR (#10) for Airbnb style, pull it down and see if the errors you see are _agreeable_ enough.

**Comment by sixlive** [comment]
Resolved via #10
