### ISSUE TITLE
Gatsby Rewrite

### ISSUE THREAD

**Issue by sixlive** [DetroitJS/detroitjs-com#40]
Would love to see this re-written for Gatsby targeted and the target host as Netlify.

**Comment by seafoam6** [comment]
That's the plan, I just gotta put in the elbow grease. <3 Gatsby

**Comment by imcodingideas** [comment]
I would love to take this responsibility. Can you assign me as the owner?

**Comment by sixlive** [comment]
I don’t know if I can without adding you to the org. It’s all you though dude! Go for it!

**Comment by imcodingideas** [comment]
OK, I'll have it done at the latest this weekend.

![screenshot 2018-09-12 16 41 00](https://user-images.githubusercontent.com/5374985/45458913-caec9d00-b6aa-11e8-9414-51d6c521b5b8.png)

Should I add the blog https://github.com/DetroitJS/detroitjs-com/pull/38 with contentful/netlify?

I should continue to use styled components?

**Comment by sixlive** [comment]
I have no opinions. Only thing I would switch is manual creation of Meetup events on the homepage for now. Maybe use the netlify cms?

**Comment by imcodingideas** [comment]
@sixlive well I just finished that part. Let's create another ticket for moving over to netlify cms for Meetup events. 

I will do that once this PR gets merged.
